_wandb:
    value:
        cli_version: 0.19.5
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.9.0
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.9.0
            "5": 0.19.5
            "8":
                - 3
                - 5
            "12": 0.19.5
            "13": windows-amd64
