num_classes: 2
rgb_in_channels: 3
ms_in_channels: 5
model_size: tiny
fusion_strategy: hierarchical
fusion_type: attention
learning_rate: 0.0001
weight_decay: 0.0001
class_weights: null
pretrained_backbone: ../checkpoints_convnext_tiny/last.ckpt
freeze_backbone: true
